name: Build and Deploy Documentation
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Package
        run: pip install .

      - name: Install Sphinx and Theme
        run: pip install sphinx sphinx_rtd_theme

      - name: Build Sphinx API Docs
        run: sphinx-apidoc -o docs/source/ metal_library/

      - name: Build Sphinx Docs
        run: sphinx-build -b html docs docs/_build/html 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html  # Corrected directory
          force_orphan: true
